/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Valentin Barros
 */
public class CargarTratamiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    private String[] nombre = {"Masajes", "Tratamiento Corporal", "Tratamiento Faciales", "Tratamiento Esteticos", "Tratamiento Relajacion"};
    private String [] masajes = {"Masaje Sueco", "Masaje de Tejido Profundo", "Masaje con Piedras Calientes", "Masajes Especializados"};
    private String[] corporal = {"Exfoliacion Corporal", "Envolturas Corporales", "Hidroterapia", "Vacumterapia"};
    private String[] faciales = {"Facial Basico", "Faciales Aavnzados", "Microdermoabrasion", "Radiofrecuencia", "Ultrasonido", "Luz Pulsada Intensa", "Vaporizador Facial"};
    private String[] esteticos = {"Manicura y Pedicura", "Depilacion", "Perfilado de Cejas"};
    private String[] relajacion = {"Circuito de aguas", "Aromaterapia", "Musicoterapia", "Terapias con aceites esenciales"};        
    
    
    /**
     * Creates new form CargaMasajista
     */
    public CargarTratamiento() {
        initComponents();
        cambiarTextField(this.jTFCodigo);
        cambiarTextField(this.jTFNombre);
        cambiarTextField(this.jTFDetalle);
        estiloComboBox(this.jCBNombre);
        estiloComboBox(this.jCBTipo);
        cargarCombo(this.jCBNombre, nombre);
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPPrincipal = new javax.swing.JPanel();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCoddigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jLDetalle = new javax.swing.JLabel();
        jTFDetalle = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jRBEstado = new javax.swing.JRadioButton();
        jBAgregar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMasajista = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jCBNombre = new javax.swing.JComboBox<>();
        jCBTipo = new javax.swing.JComboBox<>();
        jLCosto = new javax.swing.JLabel();
        jTFCosto = new javax.swing.JTextField();
        jLCSesiones = new javax.swing.JLabel();
        jTFSesiones = new javax.swing.JTextField();
        jLDuracion = new javax.swing.JLabel();
        jCBDuracion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jPPrincipal.setBackground(new java.awt.Color(249, 246, 238));

        jPTitulo.setBackground(new java.awt.Color(53, 94, 59));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(168, 213, 186));
        jLTitulo.setText("Cargar Tratamiento");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLTitulo)
                .addGap(156, 156, 156))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addGap(20, 20, 20))
        );

        jLCoddigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCoddigo.setForeground(new java.awt.Color(53, 94, 59));
        jLCoddigo.setText("Codigo:");

        jBBuscar.setBackground(new java.awt.Color(249, 246, 238));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LUPAX16.png"))); // NOI18N
        jBBuscar.setText("Buscar");

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(53, 94, 59));
        jLNombre.setText("Nombre:");

        jLDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDetalle.setForeground(new java.awt.Color(53, 94, 59));
        jLDetalle.setText("Detalle:");

        jLTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTipo.setForeground(new java.awt.Color(53, 94, 59));
        jLTipo.setText("Tipo:");

        jLEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(53, 94, 59));
        jLEstado.setText("Estado:");

        jRBEstado.setBackground(new java.awt.Color(249, 246, 238));

        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/29.png"))); // NOI18N
        jBAgregar.setToolTipText("Agregar Tratamiento");

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/30.png"))); // NOI18N
        jBModificar.setToolTipText("Modificar Tratamiento");

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31.png"))); // NOI18N
        jBEliminar.setToolTipText("Eliminar Tratamiento");

        jTMasajista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTMasajista);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jCBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNombreActionPerformed(evt);
            }
        });

        jLCosto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCosto.setForeground(new java.awt.Color(53, 94, 59));
        jLCosto.setText("Costo:");

        jLCSesiones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCSesiones.setForeground(new java.awt.Color(53, 94, 59));
        jLCSesiones.setText("Cant. Sesiones:");

        jLDuracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDuracion.setForeground(new java.awt.Color(53, 94, 59));
        jLDuracion.setText("Duracion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 94, 59));
        jLabel3.setText("Productos:");

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalir)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPPrincipalLayout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLTipo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLCoddigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBBuscar)))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLDetalle)
                                    .addGap(39, 39, 39)
                                    .addComponent(jTFDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLCSesiones)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLEstado)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRBEstado))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLDuracion)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCBDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)))
                        .addGroup(jPPrincipalLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCoddigo)
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTipo)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDetalle)
                    .addComponent(jTFDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCosto)
                    .addComponent(jLDuracion)
                    .addComponent(jCBDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCSesiones)
                        .addComponent(jTFSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLEstado))
                    .addComponent(jRBEstado))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBAgregar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNombreActionPerformed
        // TODO add your handling code here:
        if(this.jCBNombre.getSelectedItem().equals("Masajes")){
            this.jCBTipo.removeAllItems();
            cargarCombo(this.jCBTipo, masajes);
        }else{
            if(this.jCBNombre.getSelectedItem().equals("Tratamiento Corporal")){
                this.jCBTipo.removeAllItems();
                cargarCombo(this.jCBTipo, corporal);
            }else{
                if(this.jCBNombre.getSelectedItem().equals("Tratamiento Faciales")){
                    this.jCBTipo.removeAllItems();
                    cargarCombo(this.jCBTipo, faciales);
                }else{
                    if(this.jCBNombre.getSelectedItem().equals("Tratamiento Esteticos")){
                        this.jCBTipo.removeAllItems();
                        cargarCombo(this.jCBTipo, esteticos);
                    }else{
                        this.jCBTipo.removeAllItems();
                        cargarCombo(this.jCBTipo, relajacion);
                    }
                }
            }
        }
    }//GEN-LAST:event_jCBNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBDuracion;
    private javax.swing.JComboBox<String> jCBNombre;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLCSesiones;
    private javax.swing.JLabel jLCoddigo;
    private javax.swing.JLabel jLCosto;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCosto;
    private javax.swing.JTextField jTFDetalle;
    private javax.swing.JTextField jTFSesiones;
    private javax.swing.JTable jTMasajista;
    // End of variables declaration//GEN-END:variables

    private void cambiarTextField(JTextField campo) {
        Color borde = new Color(53, 94, 59);
        campo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // línea inferior
        campo.setBackground(new Color(0, 0, 0, 0)); // fondo transparente
        campo.setOpaque(false); // asegura transparencia
        campo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        campo.setForeground(Color.DARK_GRAY);
        campo.setCaretColor(Color.GRAY); // color del curso
    }

    private void cargarCombo(JComboBox<String> comboBox, String [] cbTratamientos) {
        for (int i = 0; i < cbTratamientos.length; i++) {
            comboBox.addItem(cbTratamientos[i]);
        }
    }

    private void estiloComboBox(JComboBox<String> combo) {
        Color borde = new Color(53, 94, 59);
        combo.setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
        combo.setForeground(Color.DARK_GRAY);          // Texto verde
        combo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // Línea verde abajo
        UIManager.put("ComboBox.popupBackground", Color.WHITE);

    }

    private void armarCabecera() {
        modelo.addColumn("Matricula");
        modelo.addColumn("Nombre Apellido");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Telefono");
        modelo.addColumn("Estado");
        jTMasajista.setModel(modelo);
    }
    
}
