/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Persistencia.ClienteData;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import spaentrededos.Cliente;

/**
 *
 * @author Valentin Barros
 */
public class CargarCliente extends javax.swing.JInternalFrame {

     private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
     
     ClienteData cd = new ClienteData();
    /**
     * Creates new form CargarCliente
     */
    public CargarCliente() {
        initComponents();
        cambiarTextField(this.jTFCodigo);
        cambiarTextField(this.jTFDocumento);
        cambiarTextField(this.jTFNombre);
        cambiarTextField(this.jTFTelefono);
        cambiarTextField(this.jTFEdad);
        cambiarTextField(this.jTFAfecciones);
        armarCabecera();
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLDocumento = new javax.swing.JLabel();
        jTFDocumento = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLEdad = new javax.swing.JLabel();
        jTFEdad = new javax.swing.JTextField();
        jLAfecciones = new javax.swing.JLabel();
        jTFAfecciones = new javax.swing.JTextField();
        jLEstado = new javax.swing.JLabel();
        jRBEstado = new javax.swing.JRadioButton();
        jBAgregar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();

        jPPrincipal.setBackground(new java.awt.Color(249, 246, 238));

        jPTitulo.setBackground(new java.awt.Color(53, 94, 59));

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(168, 213, 186));
        jLTitulo.setText("Carga Cliente");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLTitulo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCodigo.setForeground(new java.awt.Color(53, 94, 59));
        jLCodigo.setText("Codigo:");

        jTFCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCodigoKeyReleased(evt);
            }
        });

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LUPAX16.png"))); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLDocumento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDocumento.setForeground(new java.awt.Color(53, 94, 59));
        jLDocumento.setText("Documento:");

        jTFDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDocumentoKeyReleased(evt);
            }
        });

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(53, 94, 59));
        jLNombre.setText("Nombre y Apellido:");

        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreKeyReleased(evt);
            }
        });

        jLTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(53, 94, 59));
        jLTelefono.setText("Telefono:");

        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyReleased(evt);
            }
        });

        jLEdad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEdad.setForeground(new java.awt.Color(53, 94, 59));
        jLEdad.setText("Edad:");

        jTFEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFEdadKeyReleased(evt);
            }
        });

        jLAfecciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLAfecciones.setForeground(new java.awt.Color(53, 94, 59));
        jLAfecciones.setText("Afecciones:");

        jTFAfecciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAfeccionesKeyReleased(evt);
            }
        });

        jLEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(53, 94, 59));
        jLEstado.setText("Estado:");

        jRBEstado.setBackground(new java.awt.Color(249, 246, 238));

        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17.png"))); // NOI18N
        jBAgregar.setToolTipText("Agregar Cliente");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/18.png"))); // NOI18N
        jBModificar.setToolTipText("Modificar Cliente");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/19.png"))); // NOI18N
        jBEliminar.setToolTipText("Eliminar Cliente");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCliente);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                            .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLEstado)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRBEstado))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLAfecciones)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFAfecciones))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLTelefono)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLEdad)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFEdad))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLNombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFNombre))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLDocumento)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFDocumento))
                                .addGroup(jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLCodigo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBBuscar)))
                            .addGap(104, 104, 104))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                            .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBSalir)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDocumento)
                    .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefono)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEdad)
                    .addComponent(jTFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAfecciones)
                    .addComponent(jTFAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEstado)
                    .addComponent(jRBEstado))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[0-9_.]+");
        String nro = this.jTFCodigo.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFCodigo.setText(nro.substring(0, nro.length() - 1));
            this.jTFCodigo.requestFocus();
        }
    }//GEN-LAST:event_jTFCodigoKeyReleased

    private void jTFDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDocumentoKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[0-9_.]+");
        String nro = this.jTFDocumento.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFDocumento.setText(nro.substring(0, nro.length() - 1));
            this.jTFDocumento.requestFocus();
        }
    }//GEN-LAST:event_jTFDocumentoKeyReleased

    private void jTFTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTelefonoKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[0-9_.]+");
        String nro = this.jTFTelefono.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFTelefono.setText(nro.substring(0, nro.length() - 1));
            this.jTFTelefono.requestFocus();
        }
    }//GEN-LAST:event_jTFTelefonoKeyReleased

    private void jTFEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEdadKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[0-9_.]+");
        String nro = this.jTFEdad.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFEdad.setText(nro.substring(0, nro.length() - 1));
            this.jTFEdad.requestFocus();
        }
    }//GEN-LAST:event_jTFEdadKeyReleased

    private void jTFNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[a-zA-Z_ \\t\\n\\x0B\\f\\r]+");
        String nro = this.jTFNombre.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es una letra");
            this.jTFNombre.setText(nro.substring(0, nro.length() - 1));
            this.jTFNombre.requestFocus();
        }
    }//GEN-LAST:event_jTFNombreKeyReleased

    private void jTFAfeccionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAfeccionesKeyReleased
        // TODO add your handling code here:
        Pattern patron = Pattern.compile("[a-zA-Z_ \\t\\n\\x0B\\f\\r]+");
        String nro = this.jTFAfecciones.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es una letra");
            this.jTFAfecciones.setText(nro.substring(0, nro.length() - 1));
            this.jTFAfecciones.requestFocus();
        }
    }//GEN-LAST:event_jTFAfeccionesKeyReleased

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        try {
            if (!this.jTFCodigo.getText().isEmpty()) {
                ArrayList<Cliente>cliente = cd.listarClientes();
                for (Cliente c : cliente) {
                    if (c.getCodCli() == Integer.parseInt(this.jTFCodigo.getText())) {
                        this.jTFCodigo.setText(Integer.toString(c.getCodCli()));
                        this.jTFDocumento.setText(Integer.toString(c.getDni()));
                        this.jTFNombre.setText(c.getNombreCompleto());
                        this.jTFTelefono.setText(Integer.toString(c.getTelefono()));
                        this.jTFEdad.setText(Integer.toString(c.getEdad()));
                        this.jTFAfecciones.setText(c.getAfecciones());
                        this.jRBEstado.setSelected(c.isEstado());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo Codigo esta vacio");
            }
        } catch (NumberFormatException ex) {
            System.out.println(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(null, "Numero no valido" + ex.getMessage());
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if (!this.jTFDocumento.getText().isEmpty() && !this.jTFNombre.getText().isEmpty() && !this.jTFTelefono.getText().isEmpty() && !this.jTFEdad.getText().isEmpty() && !this.jTFAfecciones.getText().isEmpty()) {
                int documento = Integer.parseInt(this.jTFDocumento.getText());
                String nombre = this.jTFNombre.getText();
                int telefono = Integer.parseInt(this.jTFTelefono.getText());
                int edad = Integer.parseInt(this.jTFEdad.getText());
                String afecciones = this.jTFAfecciones.getText();
                boolean estado = this.jRBEstado.isSelected();
                Cliente cliente = new Cliente(documento,  nombre,  telefono,  edad, afecciones, estado);
                cd.guardarCliente(cliente);
            }
            limpiarCampos();
            modelo.setRowCount(0);
            cargarDatosTabla();
        } catch (NumberFormatException ex) {
            System.out.println(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(null, "Numero no valido" + ex.getMessage());
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        try {
            if (!this.jTFDocumento.getText().isEmpty() && !this.jTFNombre.getText().isEmpty() && !this.jTFTelefono.getText().isEmpty() && !this.jTFEdad.getText().isEmpty() && !this.jTFAfecciones.getText().isEmpty()) {
                int codigo = Integer.parseInt(this.jTFCodigo.getText());
                int documento = Integer.parseInt(this.jTFDocumento.getText());
                String nombre = this.jTFNombre.getText();
                int telefono = Integer.parseInt(this.jTFTelefono.getText());
                int edad = Integer.parseInt(this.jTFEdad.getText());
                String afecciones = this.jTFAfecciones.getText();
                boolean estado = this.jRBEstado.isSelected();
                Cliente cliente = new Cliente(codigo, documento,  nombre,  telefono,  edad, afecciones, estado);
                cd.modificarCliente(cliente);
            }
            limpiarCampos();
            modelo.setRowCount(0);
            cargarDatosTabla();
        } catch (NumberFormatException ex) {
            System.out.println(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(null, "Numero no valido" + ex.getMessage());
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        try{
            if(!this.jTFCodigo.getText().isEmpty()){
                int codigo = Integer.parseInt(this.jTFCodigo.getText());
                cd.eliminarCliente(codigo);
            }
            limpiarCampos();
            modelo.setRowCount(0);
            cargarDatosTabla();
        }catch (NumberFormatException ex) {
            System.out.println(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(null, "Numero no valido" + ex.getMessage());
        }
    }//GEN-LAST:event_jBEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLAfecciones;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDocumento;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTextField jTFAfecciones;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFDocumento;
    private javax.swing.JTextField jTFEdad;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables

private void cambiarTextField(JTextField campo) {
        Color borde = new Color(53, 94, 59);
        campo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // línea inferior
        campo.setBackground(new Color(0, 0, 0, 0)); // fondo transparente
        campo.setOpaque(false); // asegura transparencia
        campo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        campo.setForeground(Color.DARK_GRAY);
        campo.setCaretColor(Color.GRAY); // color del curso
    }

    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Documento");
        modelo.addColumn("Nombre Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("Edad");
        modelo.addColumn("Afecciones");
        modelo.addColumn("Estado");
        jTCliente.setModel(modelo);
    }
    
    private void limpiarCampos() {
        this.jTFCodigo.setText("");
        this.jTFDocumento.setText("");
        this.jTFNombre.setText("");
        this.jTFTelefono.setText("");
        this.jTFEdad.setText("");
        this.jTFAfecciones.setText("");
        this.jRBEstado.setSelected(false);
    }
    
    private void cargarDatosTabla(){
        ArrayList<Cliente> cliente = cd.listarClientes();
        for(Cliente c : cliente){
            if(c.isEstado()== true){
                modelo.addRow(new Object[]{c.getCodCli(),c.getDni(), c.getNombreCompleto(), c.getTelefono(), c.getEdad(), c.getAfecciones(), "Activo"});
            }else{
                modelo.addRow(new Object[]{c.getCodCli(),c.getDni(), c.getNombreCompleto(), c.getTelefono(), c.getEdad(), c.getAfecciones(), "Inactivo"});
            }
        }
    }
}
