/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Persistencia.ProductoData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import spaentrededos.Producto;

/**
 *
 * @author Valentin Barros
 */
public class CargarTratamiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
     private DefaultTableModel modelo1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    private String[] nombre = {"Masajes", "Tratamiento Corporal", "Tratamiento Faciales", "Tratamiento Esteticos", "Tratamiento Relajacion"};
    private String [] masajes = {"Masaje Sueco", "Masaje de Tejido Profundo", "Masaje con Piedras Calientes", "Masajes Especializados"};
    private String[] corporal = {"Exfoliacion Corporal", "Envolturas Corporales", "Hidroterapia", "Vacumterapia"};
    private String[] faciales = {"Facial Basico", "Faciales Aavnzados", "Microdermoabrasion", "Radiofrecuencia", "Ultrasonido", "Luz Pulsada Intensa", "Vaporizador Facial"};
    private String[] esteticos = {"Manicura y Pedicura", "Depilacion", "Perfilado de Cejas"};
    private String[] relajacion = {"Circuito de aguas", "Aromaterapia", "Musicoterapia", "Terapias con aceites esenciales"};  
    private String [] duracionT = {"15", "30", "45", "60", "90", "120"};
    private ArrayList<Producto> producto = new ArrayList();
    
    ProductoData pd = new ProductoData();
    
    /**
     * Creates new form CargaMasajista
     */
    public CargarTratamiento() {
        initComponents();
        cambiarTextField(this.jTFCodigo);
        cambiarTextField(this.jTFSesiones);
        cambiarTextField(this.jTFDetalle);
        cambiarTextField(this.jTFCosto);
        estiloComboBox(this.jCBNombre);
        estiloComboBox(this.jCBTipo);
        estiloComboBox(this.jCBTipo1);
        estiloComboBox(this.jCBDuracion);
        cargarCombo(this.jCBNombre, nombre);
        cargarCombo(this.jCBDuracion, duracionT);
        cargarCombo(this.jCBTipo1, nombre);
        armarCabecera();
        armarCabeceraProducto();
        datosTablaProducto(pd.listarProducto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPPrincipal = new javax.swing.JPanel();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCoddigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jLDetalle = new javax.swing.JLabel();
        jTFDetalle = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jRBEstado = new javax.swing.JRadioButton();
        jBAgregar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTratamiento = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jCBNombre = new javax.swing.JComboBox<>();
        jCBTipo = new javax.swing.JComboBox<>();
        jLCosto = new javax.swing.JLabel();
        jTFCosto = new javax.swing.JTextField();
        jLCSesiones = new javax.swing.JLabel();
        jTFSesiones = new javax.swing.JTextField();
        jLDuracion = new javax.swing.JLabel();
        jCBDuracion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCBTipo1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jRBProductos = new javax.swing.JRadioButton();
        jRRAgregados = new javax.swing.JRadioButton();
        jRBNAgregados = new javax.swing.JRadioButton();
        jBAProducto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPPrincipal.setBackground(new java.awt.Color(249, 246, 238));

        jPTitulo.setBackground(new java.awt.Color(53, 94, 59));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(168, 213, 186));
        jLTitulo.setText("Cargar Tratamiento");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLTitulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLCoddigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCoddigo.setForeground(new java.awt.Color(53, 94, 59));
        jLCoddigo.setText("Codigo:");

        jBBuscar.setBackground(new java.awt.Color(249, 246, 238));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LUPAX16.png"))); // NOI18N
        jBBuscar.setText("Buscar");

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(53, 94, 59));
        jLNombre.setText("Nombre:");

        jLDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDetalle.setForeground(new java.awt.Color(53, 94, 59));
        jLDetalle.setText("Detalle:");

        jLTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTipo.setForeground(new java.awt.Color(53, 94, 59));
        jLTipo.setText("Tipo:");

        jLEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(53, 94, 59));
        jLEstado.setText("Estado:");

        jRBEstado.setBackground(new java.awt.Color(249, 246, 238));

        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/29.png"))); // NOI18N
        jBAgregar.setToolTipText("Agregar Tratamiento");

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/30.png"))); // NOI18N
        jBModificar.setToolTipText("Modificar Tratamiento");

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31.png"))); // NOI18N
        jBEliminar.setToolTipText("Eliminar Tratamiento");

        jTTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTratamiento);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jCBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNombreActionPerformed(evt);
            }
        });

        jLCosto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCosto.setForeground(new java.awt.Color(53, 94, 59));
        jLCosto.setText("Costo:");

        jLCSesiones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCSesiones.setForeground(new java.awt.Color(53, 94, 59));
        jLCSesiones.setText("Cant. Sesiones:");

        jLDuracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDuracion.setForeground(new java.awt.Color(53, 94, 59));
        jLDuracion.setText("Duracion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 94, 59));
        jLabel3.setText("Productos:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 94, 59));
        jLabel1.setText("Tipo:");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTProductos);

        jRBProductos.setBackground(new java.awt.Color(249, 246, 238));
        jRBProductos.setText("Todos los productos");
        jRBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBProductosActionPerformed(evt);
            }
        });

        jRRAgregados.setBackground(new java.awt.Color(249, 246, 238));
        jRRAgregados.setText("Productos Agregados");
        jRRAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRAgregadosActionPerformed(evt);
            }
        });

        jRBNAgregados.setBackground(new java.awt.Color(249, 246, 238));
        jRBNAgregados.setText("Productos no Agregados");
        jRBNAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNAgregadosActionPerformed(evt);
            }
        });

        jBAProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/26.png"))); // NOI18N
        jBAProducto.setToolTipText("Agregar Producto");
        jBAProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAProductoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/28.png"))); // NOI18N
        jButton2.setToolTipText("Eliminar Porducto");

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLDetalle)
                                    .addGap(39, 39, 39)
                                    .addComponent(jTFDetalle))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLTipo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLCoddigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBBuscar)))
                                .addGap(26, 26, 26)
                                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLDuracion)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBDuracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLCSesiones)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLEstado)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBEstado))))
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRBProductos)
                                            .addComponent(jRRAgregados)
                                            .addComponent(jRBNAgregados))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBAProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCBTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLCoddigo)
                                .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCosto)
                            .addComponent(jLDuracion)
                            .addComponent(jCBDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLCSesiones)
                                .addComponent(jTFSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLEstado))
                            .addComponent(jRBEstado))))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTipo)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDetalle)
                    .addComponent(jTFDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jRBProductos)
                        .addGap(4, 4, 4)
                        .addComponent(jRRAgregados)
                        .addGap(6, 6, 6)
                        .addComponent(jRBNAgregados))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jBAProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBAgregar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNombreActionPerformed
        // TODO add your handling code here:
        if(this.jCBNombre.getSelectedItem().equals("Masajes")){
            this.jCBTipo.removeAllItems();
            cargarCombo(this.jCBTipo, masajes);
        }else{
            if(this.jCBNombre.getSelectedItem().equals("Tratamiento Corporal")){
                this.jCBTipo.removeAllItems();
                cargarCombo(this.jCBTipo, corporal);
            }else{
                if(this.jCBNombre.getSelectedItem().equals("Tratamiento Faciales")){
                    this.jCBTipo.removeAllItems();
                    cargarCombo(this.jCBTipo, faciales);
                }else{
                    if(this.jCBNombre.getSelectedItem().equals("Tratamiento Esteticos")){
                        this.jCBTipo.removeAllItems();
                        cargarCombo(this.jCBTipo, esteticos);
                    }else{
                        this.jCBTipo.removeAllItems();
                        cargarCombo(this.jCBTipo, relajacion);
                    }
                }
            }
        }
    }//GEN-LAST:event_jCBNombreActionPerformed

    private void jRBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBProductosActionPerformed
        // TODO add your handling code here:
        modelo1.setRowCount(0);
        this.jRRAgregados.setSelected(false);
        this.jRBNAgregados.setSelected(false);
        if(this.jRBProductos.isSelected()){
            datosTablaProducto(pd.listarProducto());
        }
    }//GEN-LAST:event_jRBProductosActionPerformed

    private void jRRAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRAgregadosActionPerformed
        // TODO add your handling code here:
        modelo1.setRowCount(0);
        this.jRBProductos.setSelected(false);
        this.jRBNAgregados.setSelected(false);
        if(this.jRRAgregados.isSelected()){
            datosTablaProducto(producto);
        }
    }//GEN-LAST:event_jRRAgregadosActionPerformed

    private void jRBNAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNAgregadosActionPerformed
        // TODO add your handling code here:
        modelo1.setRowCount(0);
        this.jRBProductos.setSelected(false);
        this.jRBNAgregados.setSelected(false);
        if(this.jRRAgregados.isSelected()){
            datosTablaProducto(producto);
        }
    }//GEN-LAST:event_jRBNAgregadosActionPerformed

    private void jBAProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAProductoActionPerformed
        // TODO add your handling code here:
        int  [] filas = this.jTProductos.getSelectedRows();
        for(int f : filas){
            if(f!=-1){
                int idProducto = Integer.parseInt(this.jTProductos.getValueAt(f,0).toString());
                String nombre = this.jTProductos.getValueAt(f,1).toString();
                String tipo = this.jTProductos.getValueAt(f,2).toString();
                String marca = this.jTProductos.getValueAt(f,3).toString();
                int stock = Integer.parseInt(this.jTProductos.getValueAt(f,4).toString());
                boolean estado = (Boolean) this.jTProductos.getValueAt(f,5);
            }
        }
    }//GEN-LAST:event_jBAProductoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAProducto;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBDuracion;
    private javax.swing.JComboBox<String> jCBNombre;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JComboBox<String> jCBTipo1;
    private javax.swing.JLabel jLCSesiones;
    private javax.swing.JLabel jLCoddigo;
    private javax.swing.JLabel jLCosto;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JRadioButton jRBNAgregados;
    private javax.swing.JRadioButton jRBProductos;
    private javax.swing.JRadioButton jRRAgregados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCosto;
    private javax.swing.JTextField jTFDetalle;
    private javax.swing.JTextField jTFSesiones;
    private javax.swing.JTable jTProductos;
    private javax.swing.JTable jTTratamiento;
    // End of variables declaration//GEN-END:variables

    private void cambiarTextField(JTextField campo) {
        Color borde = new Color(53, 94, 59);
        campo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // línea inferior
        campo.setBackground(new Color(0, 0, 0, 0)); // fondo transparente
        campo.setOpaque(false); // asegura transparencia
        campo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        campo.setForeground(Color.DARK_GRAY);
        campo.setCaretColor(Color.GRAY); // color del curso
    }

    private void cargarCombo(JComboBox<String> comboBox, String [] cbTratamientos) {
        for (int i = 0; i < cbTratamientos.length; i++) {
            comboBox.addItem(cbTratamientos[i]);
        }
    }
    

    private void estiloComboBox(JComboBox<String> combo) {
        Color borde = new Color(53, 94, 59);
        combo.setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
        combo.setForeground(Color.DARK_GRAY);          // Texto verde
        combo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // Línea verde abajo
        UIManager.put("ComboBox.popupBackground", Color.WHITE);

    }

    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Detalle");
        modelo.addColumn("Producto");
        modelo.addColumn("Costo");
        modelo.addColumn("Duracion");
        modelo.addColumn("Cant. Sesiones");
        modelo.addColumn("Estado");
        jTTratamiento.setModel(modelo);
    }
    
    private void armarCabeceraProducto(){
        modelo1.addColumn("idProducto");
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Tipo");
        modelo1.addColumn("Marca");
        modelo1.addColumn("Stock");
        modelo1.addColumn("Estado");
        this.jTProductos.setModel(modelo1);
    }
    
    private void datosTablaProducto(ArrayList<Producto> producto){
        for(Producto p:producto){
            if(p.isEstado()== true){
                modelo.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getTipo(), p.getMarca(), p.getStock(), "Activo"});
            }else{
                modelo.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getTipo(), p.getMarca(), p.getStock(), "Inactivo"});
            }
        }
    }
}
