/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import spaentrededos.Dia_De_Spa;
import Persistencia.Dia_De_SpaData;
import Persistencia.ClienteData;
import spaentrededos.Cliente;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Objects;
import javax.swing.JOptionPane;


/**
 *
 * @author carri
 */
public class ListarDia_De_Spa extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarDia_De_Spa
     */
    private DefaultTableModel modeloTabla;
    private Dia_De_SpaData diaDeSpaData;
    private ClienteData clienteData;
    public ListarDia_De_Spa() {
        initComponents();
        diaDeSpaData = new Dia_De_SpaData(Conexion.getConexion());
        clienteData = new Dia_De_SpaData(Conexion.getConexion());
        String[] titulos = {"Cliente", "Preferencias", "Fecha y Hora", "Monto", "Estado"};
        modeloTabla = new DefaultTableModel(null, titulos);
        jTablaSpa.setModel(modeloTabla);
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaSpa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTidDiaSpa = new javax.swing.JTextField();
        jTidCliente = new javax.swing.JTextField();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTablaSpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Preferencias ", "Fecha y Hora", "Monto", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTablaSpa);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 94, 59));
        jLabel1.setText("ID Dia Spa ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 94, 59));
        jLabel2.setText("ID Cliente");

        jPTitulo.setBackground(new java.awt.Color(53, 94, 59));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(168, 213, 186));
        jLTitulo.setText("Dia de Spa ");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addGap(234, 234, 234))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLTitulo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTidDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaSpa;
    private javax.swing.JTextField jTidCliente;
    private javax.swing.JTextField jTidDiaSpa;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTabla() {
    modeloTabla.setRowCount(0);
    try{
        List<Dia_De_Spa> listaDiasDeSpa = diaDeSpaData.listarDiasDeSpa();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        for(Dia_De_Spa diaSpa: listaDiasDeSpa){
            int codCliente = diaSpa.getCliente().getCodCli();
            Cliente cliente = clienteData.buscarClientePorId(codCliente);
            String nombreCliente = (cliente != null) ? cliente.getNombreCompleto() : "Desconocido";
            Object[] fila = new Objects[5];
            fila[0] = nombreCliente;
            fila[1] = diaSpa.getPreferencias();
            fila[2] = diaSpa.getFechaYHora().format(formatter);
            fila[3] = diaSpa.getMonto();
            fila[4] = diaSpa.isEstado() ? "Activo" : "Eliminado/Finalizado";
            modeloTabla.addRow(fila);
        }
    } catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Error al cargar la lista: " +ex.getMessage());
    }
    }
}
