/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Persistencia.InstalacionData;
import Persistencia.MasajistaData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import spaentrededos.Instalacion;
import spaentrededos.Masajista;
import spaentrededos.Sesion;

/**
 *
 * @author Valentin Barros
 */
public class ListarInstalacionesLibres extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    private String[] especialidaes = {"Facial", "Corporal", "Relajacion", "Estetico"};

    private MasajistaData masajistaData = new MasajistaData();
    InstalacionData insData=new InstalacionData();
    ArrayList<Sesion> listat =new ArrayList();
    //private MasajistaData masajistaData = new MasajistaData();
    /**
     * Creates new form CargaMasajista
     */
    public ListarInstalacionesLibres() {
        initComponents();
        cambiarTextField(this.jTFHora1);
        cambiarTextField(this.jTFHora2);
        armarCabecera();
        cargarTabla();
        HoraInstalaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jPPrincipal = new javax.swing.JPanel();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jTFHora1 = new javax.swing.JTextField();
        jLHoraio = new javax.swing.JLabel();
        jTFHora2 = new javax.swing.JTextField();
        jLA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTInstalacionesLibres = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        jPPrincipal.setBackground(new java.awt.Color(249, 246, 238));

        jPTitulo.setBackground(new java.awt.Color(53, 94, 59));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(168, 213, 186));
        jLTitulo.setText("Instalaciones Libres");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLTitulo)
                .addGap(156, 156, 156))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addGap(20, 20, 20))
        );

        jTFHora1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFHora1FocusLost(evt);
            }
        });
        jTFHora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFHora1KeyReleased(evt);
            }
        });

        jLHoraio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLHoraio.setForeground(new java.awt.Color(53, 94, 59));
        jLHoraio.setText("Intalacion libre de:");

        jTFHora2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFHora2FocusLost(evt);
            }
        });
        jTFHora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFHora2ActionPerformed(evt);
            }
        });
        jTFHora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFHora2KeyReleased(evt);
            }
        });

        jLA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLA.setForeground(new java.awt.Color(53, 94, 59));
        jLA.setText("A:");

        jTInstalacionesLibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTInstalacionesLibres);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(53, 94, 59));
        jLabel2.setText("Fecha:");

        jToggleButton1.setText("Instalacion Libre");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton1))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLHoraio)
                        .addGap(18, 18, 18)
                        .addComponent(jTFHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLA)
                        .addGap(18, 18, 18)
                        .addComponent(jTFHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLHoraio)
                        .addComponent(jLA)
                        .addComponent(jTFHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFHora1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFHora1KeyReleased

    }//GEN-LAST:event_jTFHora1KeyReleased

    private void jTFHora2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFHora2KeyReleased

    }//GEN-LAST:event_jTFHora2KeyReleased

    private void jTFHora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFHora2ActionPerformed
        insLibre();
    }//GEN-LAST:event_jTFHora2ActionPerformed

    private void jTFHora1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFHora1FocusLost
        Pattern patron = Pattern.compile("([01]?[0-9]|2[0-3]):[0-5][0-9]");
        String nro = this.jTFHora1.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFHora1.setText(nro.substring(0, nro.length() - 1));
            this.jTFHora1.requestFocus();
        }
    }//GEN-LAST:event_jTFHora1FocusLost

    private void jTFHora2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFHora2FocusLost
       Pattern patron = Pattern.compile("([01]?[0-9]|2[0-3]):[0-5][0-9]");
        String nro = this.jTFHora2.getText();
        Matcher m = patron.matcher(nro);
        if (!m.matches() && nro.length() > 0) {
            JOptionPane.showMessageDialog(this, "No es un numero");
            this.jTFHora2.setText(nro.substring(0, nro.length() - 1));
            this.jTFHora2.requestFocus();
        }
    }//GEN-LAST:event_jTFHora2FocusLost

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        insLibre();
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLA;
    private javax.swing.JLabel jLHoraio;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTFHora1;
    private javax.swing.JTextField jTFHora2;
    private javax.swing.JTable jTInstalacionesLibres;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void cambiarTextField(JTextField campo) {
        Color borde = new Color(53, 94, 59);
        campo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borde)); // línea inferior
        campo.setBackground(new Color(0, 0, 0, 0)); // fondo transparente
        campo.setOpaque(false); // asegura transparencia
        campo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        campo.setForeground(Color.DARK_GRAY);
        campo.setCaretColor(Color.GRAY); // color del curso
    }

    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Detalle");
        modelo.addColumn("Precio");
        modelo.addColumn("Estado");
        jTInstalacionesLibres.setModel(modelo);
    }

    private void limpiarCampos() {
        this.jTFHora1.setText("");
        this.jTFHora2.setText("");
       
    }
    
    private void cargarTabla(){
        ArrayList<Instalacion>lins=new ArrayList();
        lins=insData.listarInstalaciones();
        for (Instalacion i : lins) {
            if(i.isEstado()==true){
            modelo.addRow(new Object[]{i.getCodInstal(),i.getNombre(),i.getDetalleUso(),i.getPrecio30M(),"activo"});
            }else{
                modelo.addRow(new Object[]{i.getCodInstal(),i.getNombre(),i.getDetalleUso(),i.getPrecio30M(),"inactivo"});
            }
        }
        
    }

     private void insLibre (){
         try{
        //Date fechas=(Date) jDateChooser1.getDate();
        //LocalDate fecha=fechas.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        DateTimeFormatter f=DateTimeFormatter.ofPattern("H:mm");
        LocalTime horati=LocalTime.parse(jTFHora1.getText(), f);
        LocalTime horatf=LocalTime.parse(jTFHora1.getText(), f);
        ArrayList<Instalacion>inslista=(ArrayList<Instalacion>) insData.listarInstalacionesLibresHora(horati, horatf);
        
        ArrayList<Instalacion> fil=new ArrayList();
        for(Instalacion i: inslista){
            boolean c = false;
            for(Sesion s:listat){
                LocalTime horai=s.getFechaHoraInicio().toLocalTime();
                LocalTime horaf=s.getFechaHoraFin().toLocalTime();
                
                if(horai.equals(horati)&&horaf.equals(horatf)){
                    c=true;
                    break;
                }
            }
            if(c){
                fil.add(i);
            }
        }
        if(fil.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay instalacion libre");
        }else{
            for(Instalacion i:fil){
                   modelo.addRow(new Object[]{i.getCodInstal(),i.getNombre(),i.getDetalleUso(),i.getPrecio30M(),"activo"});
        }

            }
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Formato de hora invalido");
        
         }
    }
    
    private void HoraInstalaciones (){
        ArrayList<Instalacion>hlista=new ArrayList();
        hlista=insData.listarInstalaciones();
        
        for (Instalacion i: hlista) {
            if(i.getCodInstal()==1){
                Sesion bañot=new Sesion(LocalDateTime.of(2025, 11, 18, 9, 0),LocalDateTime.of(2025, 11, 18, 10, 0),i);
                listat.add(bañot);
            }else if(i.getCodInstal()==2){
                Sesion ducha=new Sesion(LocalDateTime.of(2025, 11, 18, 10, 0),LocalDateTime.of(2025, 11, 18, 11, 0),i);
                listat.add(ducha);
            }else if(i.getCodInstal()==3){
                Sesion hidro=new Sesion(LocalDateTime.of(2025, 11, 18, 11, 0),LocalDateTime.of(2025, 11, 18, 12, 0),i);
                listat.add(hidro);
            }else if(i.getCodInstal()==4){
                Sesion jacuzzi=new Sesion(LocalDateTime.of(2025, 11, 18, 12, 0),LocalDateTime.of(2025, 11, 18, 13, 0),i);
                listat.add(jacuzzi);
            }else if(i.getCodInstal()==5){
                Sesion piscina=new Sesion(LocalDateTime.of(2025, 11, 18, 13, 0),LocalDateTime.of(2025, 11, 18, 14, 0),i);
                listat.add(piscina);
            }else if(i.getCodInstal()==6){
                Sesion sauna=new Sesion(LocalDateTime.of(2025, 11, 18, 14, 0),LocalDateTime.of(2025, 11, 18, 15, 0),i);
                listat.add(sauna);
            }else if(i.getCodInstal()==7){
                Sesion zrelax=new Sesion(LocalDateTime.of(2025, 11, 18, 15, 0),LocalDateTime.of(2025, 11, 18, 16, 0),i);
                listat.add(zrelax);
            }
        }
    }

}




