/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Persistencia.entidadData;
import javax.swing.JOptionPane;
import spaentrededos.Cliente;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    private entidadData entidadData;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarCliente();
    }
public Menu(entidadData entidadData){
    initComponents();
    this.entidadData = entidadData;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGestionClientes = new javax.swing.JLabel();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldIngresarCodigo = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldIngresarDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldIngresarNombre = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldIngresarTelefono = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldIngresarEdad = new javax.swing.JTextField();
        jLabelAfecciones = new javax.swing.JLabel();
        jTextFieldIngresarAfecciones = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldIngresarEstado = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGestionClientes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelGestionClientes.setText("Gestion de clientes");

        jButtonInsertar.setText("Insertar");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelCodigo.setText("Codigo:");

        jTextFieldIngresarCodigo.setEditable(false);
        jTextFieldIngresarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarCodigoActionPerformed(evt);
            }
        });

        jLabelDNI.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelDNI.setText("DNI:");

        jTextFieldIngresarDNI.setEditable(false);

        jLabelNombre.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre completo:");

        jTextFieldIngresarNombre.setEditable(false);

        jLabelTelefono.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelTelefono.setText("Telefono:");

        jTextFieldIngresarTelefono.setEditable(false);

        jLabelEdad.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelEdad.setText("Edad:");

        jTextFieldIngresarEdad.setEditable(false);

        jLabelAfecciones.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelAfecciones.setText("Afecciones:");

        jTextFieldIngresarAfecciones.setEditable(false);

        jLabelEstado.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabelEstado.setText("Estado:");

        jTextFieldIngresarEstado.setEditable(false);

        jButtonAlta.setText("Dar alta");

        jButtonBaja.setText("Dar baja");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAfecciones)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIngresarAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIngresarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIngresarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBaja)
                            .addComponent(jButtonActualizar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAlta))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelEdad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldIngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)
                                            .addComponent(jLabelEstado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldIngresarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonInsertar)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonBuscar)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelTelefono)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldIngresarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGestionClientes)
                        .addGap(93, 93, 93)))
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelGestionClientes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldIngresarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTextFieldIngresarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldIngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldIngresarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAfecciones)
                    .addComponent(jTextFieldIngresarAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEdad)
                    .addComponent(jLabelEstado)
                    .addComponent(jTextFieldIngresarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonActualizar))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonBaja))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonInsertarActionPerfomed(java.awt.event.ActionEvent evt){
    try{
        String nombre = jTextFieldIngresarNombre.getText();
        String dni = jTextFieldIngresarDNI.getText();
        String telefono = jTextFieldIngresarTelefono.getText();
        int edad = Integer.parseInt(jTextFieldIngresarEdad.getText());
        boolean estado = true;
        Cliente nuevoCliente = new Cliente(0, edad, dni, telefono, nombre, "Ninguna", estado);
        entidadData.guardarCliente(nuevoCliente);
        JOptionPane.showMessageDialog(this, "Cliente insertado con exito.", "Exito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
        cargarClientesEnComboBox();
    } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Error en el formato de datos(Edad debe ser un numero).", "Error", JOptionPane.ERROR_MESSAGE);
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error al insertar el cliente: " +e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        try{
            String codigoTexto = jTextFieldIngresarCodigo.getText();
            if(codigoTexto.isEmpty()){
                JOptionPane.showMessageDialog(this, "Debe buscar o seleccionar un cliente primero(el campo de codigo debe estar lleno).", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
        int codigo = Integer.parseInt(codigoTexto);
        int dni = Integer.parseInt(jTextFieldIngresarDNI.getText());
        String nombre = jTextFieldIngresarNombre.getText();
        int telefono = Integer.parseInt(jTextFieldIngresarTelefono.getText());
        int edad = Integer.parseInt(jTextFieldIngresarEdad.getText());
        String afecciones = jTextFieldIngresarAfecciones.getText();
        boolean estado = Boolean.parseBoolean(jTextFieldIngresarEstado.getText());
        Cliente clienteActualizado = new Cliente(codigo, dni, nombre, telefono, edad, afecciones, estado);
        entidadData.actualizarCliente(clienteActualizado);
        JOptionPane.showMessageDialog(this, "Cliente actualizado con exito.", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error en el formato de datos: DNI, Codigo, Telefono o Edad deben ser numeros." +e.getMessage(), "Error de formato.", JOptionPane.ERROR_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al actualizar el cliente: " +e.getMessage(), "Error de actualizacion.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextFieldIngresarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarCodigoActionPerformed
        // TODO add your handling code here:
        try{
            String codigoTexto = jTextFieldIngresarCodigo.getText();
            if(!codigoTexto.isEmpty()){
                int idCliente = Integer.parseInt(codigoTexto);
                Cliente clienteEncontrado = entidadData.buscarCliente(idCliente);
                if(clienteEncontrado != null){
                    jTextFieldIngresarDNI.setText(String.valueOf(clienteEncontrado.getDni()));
                    JOptionPane.showMessageDialog(this, "Cliente encontrado por codigo.", "Busqueda", JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(this, "Cliente con codigo " +idCliente+ " no encontrado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un numero entero valido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al buscar el cliente por codigo: " +e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldIngresarCodigoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem() != null){
        Cliente cliente = (Cliente)jComboBox1.getSelectedItem();
        jTextFieldIngresarCodigo.setText(String.valueOf(cliente.getCodCli()));
        jTextFieldIngresarDNI.setText(String.valueOf(cliente.getDni()));
        jTextFieldIngresarNombre.setText(cliente.getNombreCompleto());
        jTextFieldIngresarTelefono.setText(String.valueOf(cliente.getTelefono()));
        jTextFieldIngresarEdad.setText(String.valueOf(cliente.getEdad()));
        jTextFieldIngresarAfecciones.setText(cliente.getAfecciones());
        jTextFieldIngresarEstado.setText(String.valueOf(cliente.isEstado()));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JComboBox<Cliente> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelAfecciones;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelGestionClientes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextFieldIngresarAfecciones;
    private javax.swing.JTextField jTextFieldIngresarCodigo;
    private javax.swing.JTextField jTextFieldIngresarDNI;
    private javax.swing.JTextField jTextFieldIngresarEdad;
    private javax.swing.JTextField jTextFieldIngresarEstado;
    private javax.swing.JTextField jTextFieldIngresarNombre;
    private javax.swing.JTextField jTextFieldIngresarTelefono;
    // End of variables declaration//GEN-END:variables
private void cargarCliente(){
    jComboBox1.addItem(new Cliente(1,44738237,"Castro Maximiliano",26601927,20,"Ninguna", true));
    jComboBox1.addItem(new Cliente(2,40238734,"Barros Edgardo",26632763,26,"Ninguna", true));
    jComboBox1.addItem(new Cliente(3,41934744,"Carrizo Anna",266387424,24,"Ninguna", true));
    jComboBox1.addItem(new Cliente(4,40238274,"Gimenez Pablo",266372834,23,"Ninguna", true));
    jComboBox1.addItem(new Cliente(5,42293843,"Fernandez Rodrigo",26635233,24,"Ninguna", true));
}

    private void limpiarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void cargarClientesEnComboBox() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
