/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ClasesAuxiliares.EscritorioPersonalizado;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Valentin Barros
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
     private EscritorioPersonalizado escritorio;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMBMenu = new javax.swing.JMenuBar();
        jMCliente = new javax.swing.JMenu();
        jMICliente = new javax.swing.JMenuItem();
        jMMasajista = new javax.swing.JMenu();
        jMIMasajista = new javax.swing.JMenuItem();
        jMIHorarios = new javax.swing.JMenuItem();
        jMSpa = new javax.swing.JMenu();
        jMICTratamiento = new javax.swing.JMenuItem();
        jMIInforme = new javax.swing.JMenuItem();
        jMInstalaciones = new javax.swing.JMenu();
        jMICConsultorio = new javax.swing.JMenuItem();
        jMICInstalaciones = new javax.swing.JMenuItem();
        jMIILibre = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );

        jMCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        jMCliente.setText("Cliente");

        jMICliente.setText("Cargar Cliente");
        jMICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMICliente);

        jMBMenu.add(jMCliente);

        jMMasajista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bodyX32.png"))); // NOI18N
        jMMasajista.setText("Masajista");

        jMIMasajista.setText("Cargar Masajista");
        jMIMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMasajistaActionPerformed(evt);
            }
        });
        jMMasajista.add(jMIMasajista);

        jMIHorarios.setText("Horarios de Masajista");
        jMIHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIHorariosActionPerformed(evt);
            }
        });
        jMMasajista.add(jMIHorarios);

        jMBMenu.add(jMMasajista);

        jMSpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/spa_5099674.png"))); // NOI18N
        jMSpa.setText("Spa");

        jMICTratamiento.setText("Cargar Tratamiento");
        jMICTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICTratamientoActionPerformed(evt);
            }
        });
        jMSpa.add(jMICTratamiento);

        jMIInforme.setText("Informe Dia de Spa");
        jMIInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInformeActionPerformed(evt);
            }
        });
        jMSpa.add(jMIInforme);

        jMBMenu.add(jMSpa);

        jMInstalaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/beauty-saloon_11279019 (1).png"))); // NOI18N
        jMInstalaciones.setText("Instalaciones");

        jMICConsultorio.setText("Cargar Consultorio");
        jMICConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICConsultorioActionPerformed(evt);
            }
        });
        jMInstalaciones.add(jMICConsultorio);

        jMICInstalaciones.setText("Cargar Instalciones");
        jMICInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICInstalacionesActionPerformed(evt);
            }
        });
        jMInstalaciones.add(jMICInstalaciones);

        jMIILibre.setText("Instalaciones Libres");
        jMIILibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIILibreActionPerformed(evt);
            }
        });
        jMInstalaciones.add(jMIILibre);

        jMBMenu.add(jMInstalaciones);

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jMSalir.setText("Salir");

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMISalir);

        jMBMenu.add(jMSalir);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMasajistaActionPerformed
        // TODO add your handling code here:escritorio.removeAll();
        escritorio.removeAll();
        escritorio.repaint();
        CargaMasajista form = new CargaMasajista();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIMasajistaActionPerformed

    private void jMIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargarCliente form = new CargarCliente();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIClienteActionPerformed

    private void jMICInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICInstalacionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargarInstalaciones form = new CargarInstalaciones();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMICInstalacionesActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        // TODO add your handling code here:\
        dispose();
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMICConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICConsultorioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargarConsultorio form = new CargarConsultorio();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMICConsultorioActionPerformed

    private void jMICTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICTratamientoActionPerformed
        // TODO add your handling code here:
        /*escritorio.removeAll();
        escritorio.repaint();
        CargarTratamiento form = new CargarTratamiento();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);*/
    }//GEN-LAST:event_jMICTratamientoActionPerformed

    private void jMIHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIHorariosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListarMasajistasPorHorario form = new ListarMasajistasPorHorario();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIHorariosActionPerformed

    private void jMIILibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIILibreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListarInstalacionesLibres form = new ListarInstalacionesLibres();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIILibreActionPerformed

    private void jMIInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInformeActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListarInformes form = new ListarInformes();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMICConsultorio;
    private javax.swing.JMenuItem jMICInstalaciones;
    private javax.swing.JMenuItem jMICTratamiento;
    private javax.swing.JMenuItem jMICliente;
    private javax.swing.JMenuItem jMIHorarios;
    private javax.swing.JMenuItem jMIILibre;
    private javax.swing.JMenuItem jMIInforme;
    private javax.swing.JMenuItem jMIMasajista;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMInstalaciones;
    private javax.swing.JMenu jMMasajista;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMSpa;
    // End of variables declaration//GEN-END:variables

public class FondoDesktopPane extends JDesktopPane {
    private Image imagenFondo;

    public FondoDesktopPane(String rutaImagen) {
        imagenFondo = new ImageIcon(rutaImagen).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
    }
}

}
